// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckPort(arg1:number,arg2:string):Promise<string>;

export function ClearArchiveCache():Promise<main.ArchiveCacheInfo>;

export function ClearOfficePreviewCache():Promise<void>;

export function CreateInvite(arg1:number,arg2:boolean):Promise<main.Invite>;

export function CreateTemporaryAccess(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<main.TemporaryView>;

export function CreateUser(arg1:string,arg2:string,arg3:boolean):Promise<main.UserView>;

export function DeleteUser(arg1:string):Promise<void>;

export function EmptyTrash():Promise<void>;

export function GetArchiveDrives():Promise<Array<main.ArchiveDriveInfo>>;

export function GetDashboard():Promise<main.Dashboard>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.Status>;

export function GetVersion():Promise<string>;

export function InspectArchiveCache(arg1:string):Promise<main.ArchiveCacheInfo>;

export function ListInvites():Promise<Array<main.Invite>>;

export function ListTemporaryAccess():Promise<Array<main.TemporaryView>>;

export function ListTrash():Promise<Array<main.trashMeta>>;

export function ListUsers():Promise<Array<main.UserView>>;

export function OfficePreviewStatus():Promise<string>;

export function OpenArchiveCacheFolder():Promise<void>;

export function OpenLibreOfficeDownload():Promise<void>;

export function RestoreTrash(arg1:string):Promise<void>;

export function RevokeInvite(arg1:string):Promise<void>;

export function RevokeTemporaryAccess(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SelectArchiveCacheFolder():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectTemporaryFolder():Promise<string>;

export function SetUserEnabled(arg1:string,arg2:boolean):Promise<void>;

export function Start():Promise<main.Status>;

export function Stop():Promise<main.Status>;
