// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CADPreviewStatus() {
  return window['go']['main']['App']['CADPreviewStatus']();
}

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function ClearCADPreviewCache() {
  return window['go']['main']['App']['ClearCADPreviewCache']();
}

export function ClearOfficePreviewCache() {
  return window['go']['main']['App']['ClearOfficePreviewCache']();
}

export function CreateInvite(arg1, arg2) {
  return window['go']['main']['App']['CreateInvite'](arg1, arg2);
}

export function CreateTemporaryAccess(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTemporaryAccess'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallCADPreviewEngine() {
  return window['go']['main']['App']['InstallCADPreviewEngine']();
}

export function ListInvites() {
  return window['go']['main']['App']['ListInvites']();
}

export function ListTemporaryAccess() {
  return window['go']['main']['App']['ListTemporaryAccess']();
}

export function ListTrash() {
  return window['go']['main']['App']['ListTrash']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function OfficePreviewStatus() {
  return window['go']['main']['App']['OfficePreviewStatus']();
}

export function OpenLibreOfficeDownload() {
  return window['go']['main']['App']['OpenLibreOfficeDownload']();
}

export function RestoreTrash(arg1) {
  return window['go']['main']['App']['RestoreTrash'](arg1);
}

export function RevokeInvite(arg1) {
  return window['go']['main']['App']['RevokeInvite'](arg1);
}

export function RevokeTemporaryAccess(arg1) {
  return window['go']['main']['App']['RevokeTemporaryAccess'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectTemporaryFolder() {
  return window['go']['main']['App']['SelectTemporaryFolder']();
}

export function SetUserEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetUserEnabled'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
